version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: cookbook_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5433:${POSTGRES_PORT}"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    container_name: cookbook_backend
    build:
      context: ../../backend
      target: dev
    restart: unless-stopped
    environment:
      PORT: ${BACKEND_PORT}
      NODE_ENV: ${NODE_ENV}
      FRONTEND_ORIGIN: ${FRONTEND_ORIGIN}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
      DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"
    volumes:
      - ../../backend:/app
      - /app/node_modules
    depends_on:
      - postgres

  frontend:
    container_name: cookbook_frontend
    build:
      context: ../../frontend
      target: dev
    restart: unless-stopped
    environment:
      VITE_API_BASE_URL: ${BACKEND_URL}
    ports:
      - "${FRONTEND_PORT}:5173"
    volumes:
      - ../../frontend:/app
      - /app/node_modules
    depends_on:
      - backend

  pgadmin:
    container_name: cookbook_pgadmin
    image: dpage/pgadmin4
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "${PGADMIN_DEFAULT_PORT}:80"
    depends_on:
      - postgres

volumes:
  postgres_data:
